### ISSUE TITLE
Design the database.

### ISSUE THREAD

**Issue by Ridmel** [Githance/backend#12]

**Comment by Ridmel** [comment]
@apfirsov @Senkdar 
Долго думал, рассматривал разные варианты реализации разделения прав. Все же для МВП остановился на самом простом - через поле choice в модели Role, т.е. обычным списком ("owner", "manager", "member"). Т.е. любая роль будет иметь одно из этих прав. А проверка в джанго будет самая стандартная, как делали в ЯП.  

![Image](https://user-images.githubusercontent.com/80767090/209813112-5a034d64-08f9-41dd-b3d5-68a337826025.jpeg)

 Дальше по ходу проекта можно будет перейти на более сложную модель. 

![Image](https://user-images.githubusercontent.com/80767090/209813169-d52c145f-611b-4209-8f4f-46f377258684.jpeg)

**Comment by Ridmel** [comment]
@apfirsov @Senkdar 
Хотел бы услышать какие-то вопросы, замечания, предложения.

**Comment by Senkdar** [comment]
Выглядит вполне логично, думаю одной роли хватит) а если потребуется впоследствии, то еще прикрутим что-нибудь
