### ISSUE TITLE
Implement vacancy creation

### ISSUE THREAD

**Issue by Ridmel** [Githance/backend#47]
- создать модель `Vacancy`, согласно схемы. Поле `description` необязательное.  Констрейнт уникальности: `(project_id, profession_id, description)`, если `deleted_at` не `Null`.
<details>
  <summary>Скрин схемы</summary>

  ![image](https://user-images.githubusercontent.com/80767090/229633948-7fa217ed-7fbf-426e-a0cf-3f62c21e428e.png)

</details>

- реализовать эндпоинты:
  `POST .../projects/{id}/vacancies/`
  `GET .../projects/{id}/vacancies/`
  `GET .../projects/{id}/vacancies/{id}/`
  `PATCH .../projects/{id}/vacancies/{id}/`, где можно изменить описание и профессию
  `DELETE .../projects/{id}/vacancies/{id}/`, пока просто проставляем `deleted_at`

**Comment by apfirsov** [comment]
Done #53
